from functools import partial

from src.populate_csv_files.get_article_content.ethglobal_hackathon.docs_parsers import crawl_sidebar, crawl_chainlink, fetch_sidebar_urls_wihtout_href
from src.populate_csv_files.get_article_content.utils import html_to_markdown_docs_chainlink

site_configs = {
    'eigenlayer': {
        'base_url': 'https://docs.eigenlayer.xyz/eigenlayer/overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'galadriel': {
        'base_url': 'https://docs.galadriel.com/overview',
        'content_selector': '#content-area',
        'img_selector': "div[class*='prose'] img",
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.lg\:text-sm'),  # Directly reference the specific crawl function
    },
    'chainlink': {
        'base_url': 'https://docs.chain.link/ccip#overview',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-ccip',
    },
    'chainlink_data_feeds': {
        'base_url': 'https://docs.chain.link/data-feeds',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-data_feeds',
    },
    'chainlink_data_streams': {
        'base_url': 'https://docs.chain.link/data-streams',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-data_streams',
    },
    'chainlink_functions': {
        'base_url': 'https://docs.chain.link/chainlink-functions',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-functions',
    },
    'chainlink_automation': {
        'base_url': 'https://docs.chain.link/chainlink-automation',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-automation',
    },
    'chainlink_vrf': {
        'base_url': 'https://docs.chain.link/vrf',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-vrf',
    },
    'nethermind': {
        'base_url': 'https://docs.nethermind.io',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'blockscout': {
        'base_url': 'https://docs.blockscout.com',
        'content_selector': 'main.flex-1',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),  # Directly reference the specific crawl function
    },
    'pimlico_permissionless': {
        'base_url': 'https://docs.pimlico.io/permissionless',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),
        'base_name': '-permissionless',
    },
    'pimlico_bundler': {
        'base_url': 'https://docs.pimlico.io/bundler',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),
        'base_name': '-bundler',
    },
    'pimlico_paymaster': {
        'base_url': 'https://docs.pimlico.io/paymaster',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'base_name': '-paymaster',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),

    },
    'argent': {
        'base_url': 'https://docs.argent.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': 'picture.relative',
        'base_name': '',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative'),
    },
    'Obol': {
        'base_url': 'https://docs.obol.tech/docs/int/Overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'lido': {
        'base_url': 'https://docs.lido.fi/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'giza_datasets': {
        'base_url': 'https://datasets.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_orion': {
        'base_url': 'https://orion.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_cli': {
        'base_url': 'https://cli.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_actions': {
        'base_url': 'https://actions.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'cairo': {
        'base_url': 'https://docs.cairo-lang.org/',
        'content_selector': '.doc',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.next > a:nth-child(1)',
    },
    'circle_stablecoins': {
        'base_url': 'https://developers.circle.com/stablecoins/',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_w3s': {
            'base_url': 'https://developers.circle.com/w3s/docs/circle-programmable-wallets-an-overview',
            'content_selector': '.rm-Article',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_mint': {
            'base_url': 'https://developers.circle.com/circle-mint/docs/introducing-circle-mint',
            'content_selector': '.rm-Article',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_verite': {
        'base_url': 'https://developers.circle.com/verite/docs/verite-protocol-introduction',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'hyperlane': {
        'base_url': 'https://docs.hyperlane.xyz/docs/intro',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'safe_home': {
        'base_url': 'https://docs.safe.global/home/what-is-safe',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'safe_sdk': {
        'base_url': 'https://docs.safe.global/sdk/overview',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'safe_advanced': {
        'base_url': 'https://docs.safe.global/advanced/api-service-architecture',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'farcaster': {
        'base_url': 'https://docs.farcaster.xyz/',
        'content_selector': '.main',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
    },
    'near_concepts': {
        'base_url': 'https://docs.near.org/concepts/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_web3_apps': {
        'base_url': 'https://docs.near.org/develop/web3-apps/whatareweb3apps',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_tools': {
        'base_url': 'https://docs.near.org/tools/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_contracts': {
        'base_url': 'https://docs.near.org/develop/contracts/whatisacontract',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_tutorials': {
        'base_url': 'https://docs.near.org/tutorials/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'celo': {
        'base_url': 'https://docs.celo.org/developer',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'base': {
        'base_url': 'https://docs.base.org/',
        'content_selector': '.docItemContainer_Rv5Z',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu', selenium=True),
    },
    'dynamic': {
        'base_url': 'https://docs.dynamic.xyz/introduction/welcome',
        'content_selector': '#content-area',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.lg\:text-sm > ul:nth-child(2)'),
    },
    'aztec': {
        'base_url': 'https://docs.aztec.network/',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
    },
    'layerzero': {
        'base_url': 'https://docs.layerzero.network/',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'fhenix': {
        'base_url': 'https://docs.fhenix.zone/docs/devdocs/intro',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-devdocs',
    },
    'fhenix_tutorial': {
        'base_url': 'https://docs.fhenix.zone/docs/tutorial/intro',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-tutorial',
    },
    'morpho': {
        'base_url': 'https://docs.morpho.org/concepts/overview/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-concepts',
    },
    'morpho_sdks': {
        'base_url': 'https://docs.morpho.org/sdks/overview/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-sdks',
    },
    'morpho_contracts': {
        'base_url': 'https://docs.morpho.org/contracts/morpho-blue/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-contracts',
    },
    'voyager': {
        'base_url': 'https://docs.voyager.online/#get-/classes',
        'content_selector': '#the-main-body > main',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nav-scroll', selenium=True, robust=True),
    },
    'worldcoin': {
        'base_url': 'https://docs.worldcoin.org/',
        'content_selector': '.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.lg\:block > ul:nth-child(1)'),
    },
    'chilliz': {
        'base_url': 'https://docs.chiliz.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'filecoin': {
        'base_url': 'https://docs.filecoin.io/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'ipc': {
        'base_url': 'https://docs.ipc.space/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'celestia_learn': {
        'base_url': 'https://docs.celestia.org/learn/how-celestia-works/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-learn',
    },
    'celestia_nodes': {
        'base_url': 'https://docs.celestia.org/nodes/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-nodes',
    },
    'celestia_developers': {
        'base_url': 'https://docs.celestia.org/developers/build-modular',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-developers',
    },
    'celestia_community': {
        'base_url': 'https://docs.celestia.org/community/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-community',
    },
    'availproject': {
        'base_url': 'https://docs.availproject.org/docs/introduction-to-avail',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container'),
    },
    'web3auth': {
        'base_url': 'https://web3auth.io/docs/sdk/pnp/web/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'ens_learn': {
        'base_url': 'https://docs.ens.domains/learn/protocol',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-learn',
    },
    'ens_web': {
        'base_url': 'https://docs.ens.domains/web/resolution',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-web',
    },
    'ens_registry': {
        'base_url': 'https://docs.ens.domains/registry/ens',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-registry',
    },
    'ens_resolver': {
        'base_url': 'https://docs.ens.domains/resolvers/public',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-resolver',
    },
    'ens_dao': {
        'base_url': 'https://docs.ens.domains/dao',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-dao',
    },
    'ens_ensip': {
        'base_url': 'https://docs.ens.domains/ensip/',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-ensip',
    },
    'gnark_howto': {
        'base_url': 'https://docs.gnark.consensys.io/category/how-to',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-howto',
    },
    'gnark_reference': {
        'base_url': 'https://docs.gnark.consensys.io/Reference/api',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-reference',
    },
    'gnark_concepts': {
        'base_url': 'https://docs.gnark.consensys.io/category/concepts',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-concepts',
    },
    'circom': {
        'base_url': 'https://docs.circom.io/getting-started/installation/',
        'content_selector': '.md-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.md-nav__item--section > nav:nth-child(3) > ul:nth-child(2)', selenium=True),
        'fetch_sidebar_func': fetch_sidebar_urls_wihtout_href
    },
    'suave': {
        'base_url': 'https://suave-alpha.flashbots.net/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'flashbots': {
        'base_url': 'https://docs.flashbots.net/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
}
