from functools import partial

from src.populate_csv_files.get_article_content.ethglobal_hackathon.docs_parsers import crawl_sidebar, crawl_chainlink, fetch_sidebar_urls_wihtout_href
from src.populate_csv_files.get_article_content.utils import html_to_markdown_docs_chainlink

site_configs = {
    'eigenlayer': {
        'base_url': 'https://docs.eigenlayer.xyz/eigenlayer/overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'galadriel': {
        'base_url': 'https://docs.galadriel.com/overview',
        'content_selector': '#content-area',
        'img_selector': "div[class*='prose'] img",
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.lg\:text-sm'),  # Directly reference the specific crawl function
    },
    'chainlink': {
        'base_url': 'https://docs.chain.link/ccip#overview',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-ccip',
    },
    'chainlink_data_feeds': {
        'base_url': 'https://docs.chain.link/data-feeds',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-data_feeds',
    },
    'chainlink_data_streams': {
        'base_url': 'https://docs.chain.link/data-streams',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-data_streams',
    },
    'chainlink_functions': {
        'base_url': 'https://docs.chain.link/chainlink-functions',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-functions',
    },
    'chainlink_automation': {
        'base_url': 'https://docs.chain.link/chainlink-automation',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-automation',
    },
    'chainlink_vrf': {
        'base_url': 'https://docs.chain.link/vrf',
        'content_selector': '#article',
        'img_selector': "img",
        'html_parser': html_to_markdown_docs_chainlink,
        'crawl_func': crawl_chainlink,  # Directly reference the specific crawl function
        'base_name': '-vrf',
    },
    'nethermind': {
        'base_url': 'https://docs.nethermind.io',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'blockscout': {
        'base_url': 'https://docs.blockscout.com',
        'content_selector': 'main.flex-1',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),  # Directly reference the specific crawl function
    },
    'pimlico_permissionless': {
        'base_url': 'https://docs.pimlico.io/permissionless',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),
        'base_name': '-permissionless',
    },
    'pimlico_bundler': {
        'base_url': 'https://docs.pimlico.io/bundler',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),
        'base_name': '-bundler',
    },
    'pimlico_paymaster': {
        'base_url': 'https://docs.pimlico.io/paymaster',
        'content_selector': '.vocs_Content',
        'img_selector': 'picture.relative',
        'base_name': '-paymaster',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.vocs_Sidebar_group'),

    },
    'argent': {
        'base_url': 'https://docs.argent.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': 'picture.relative',
        'base_name': '',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative'),
    },
    'Obol': {
        'base_url': 'https://docs.obol.tech/docs/int/Overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'lido': {
        'base_url': 'https://docs.lido.fi/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'giza_datasets': {
        'base_url': 'https://datasets.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_orion': {
        'base_url': 'https://orion.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_cli': {
        'base_url': 'https://cli.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'giza_actions': {
        'base_url': 'https://actions.gizatech.xyz/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'cairo': {
        'base_url': 'https://docs.cairo-lang.org/',
        'content_selector': '.doc',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.next > a:nth-child(1)',
    },
    'circle_stablecoins': {
        'base_url': 'https://developers.circle.com/stablecoins/',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_w3s': {
            'base_url': 'https://developers.circle.com/w3s/docs/circle-programmable-wallets-an-overview',
            'content_selector': '.rm-Article',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_mint': {
            'base_url': 'https://developers.circle.com/circle-mint/docs/introducing-circle-mint',
            'content_selector': '.rm-Article',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'circle_verite': {
        'base_url': 'https://developers.circle.com/verite/docs/verite-protocol-introduction',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.Sidebar1t2G1ZJq-vU1'),
    },
    'hyperlane': {
        'base_url': 'https://docs.hyperlane.xyz/docs/intro',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'safe_home': {
        'base_url': 'https://docs.safe.global/home/what-is-safe',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'safe_sdk': {
        'base_url': 'https://docs.safe.global/sdk/overview',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'safe_advanced': {
        'base_url': 'https://docs.safe.global/advanced/api-service-architecture',
        'content_selector': 'main.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-menu-desktop'),
    },
    'farcaster': {
        'base_url': 'https://docs.farcaster.xyz/',
        'content_selector': '.main',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
    },
    'near_concepts': {
        'base_url': 'https://docs.near.org/concepts/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_web3_apps': {
        'base_url': 'https://docs.near.org/develop/web3-apps/whatareweb3apps',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_tools': {
        'base_url': 'https://docs.near.org/tools/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_contracts': {
        'base_url': 'https://docs.near.org/develop/contracts/whatisacontract',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'near_tutorials': {
        'base_url': 'https://docs.near.org/tutorials/welcome',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'celo': {
        'base_url': 'https://docs.celo.org/developer',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'base': {
        'base_url': 'https://docs.base.org/',
        'content_selector': '.docItemContainer_Rv5Z',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu', selenium=True),
    },
    'dynamic': {
        'base_url': 'https://docs.dynamic.xyz/introduction/welcome',
        'content_selector': '#content-area',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.lg\:text-sm > ul:nth-child(2)'),
    },
    'aztec': {
        'base_url': 'https://docs.aztec.network/',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
    },
    'layerzero': {
        'base_url': 'https://docs.layerzero.network/',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'fhenix': {
        'base_url': 'https://docs.fhenix.zone/docs/devdocs/intro',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-devdocs',
    },
    'fhenix_tutorial': {
        'base_url': 'https://docs.fhenix.zone/docs/tutorial/intro',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-tutorial',
    },
    'morpho': {
        'base_url': 'https://docs.morpho.org/concepts/overview/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-concepts',
    },
    'morpho_sdks': {
        'base_url': 'https://docs.morpho.org/sdks/overview/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-sdks',
    },
    'morpho_contracts': {
        'base_url': 'https://docs.morpho.org/contracts/morpho-blue/',
        'content_selector': '.docItemContainer_pt6k',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-contracts',
    },
    'voyager': {
        'base_url': 'https://docs.voyager.online/#get-/classes',
        'content_selector': '#the-main-body > main',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nav-scroll', selenium=True, robust=True),
    },
    'worldcoin': {
        'base_url': 'https://docs.worldcoin.org/',
        'content_selector': '.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.lg\:block > ul:nth-child(1)'),
    },
    'chilliz': {
        'base_url': 'https://docs.chiliz.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'filecoin': {
        'base_url': 'https://docs.filecoin.io/',
        'content_selector': 'main.flex-1',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'ipc': {
        'base_url': 'https://docs.ipc.space/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.pt-4 > ul:nth-child(1)'),
    },
    'celestia_learn': {
        'base_url': 'https://docs.celestia.org/learn/how-celestia-works/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-learn',
    },
    'celestia_nodes': {
        'base_url': 'https://docs.celestia.org/nodes/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-nodes',
    },
    'celestia_developers': {
        'base_url': 'https://docs.celestia.org/developers/build-modular',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-developers',
    },
    'celestia_community': {
        'base_url': 'https://docs.celestia.org/community/overview',
        'content_selector': '.VPDoc',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#VPSidebarNav'),
        'base_name': '-community',
    },
    'availproject': {
        'base_url': 'https://docs.availproject.org/docs/introduction-to-avail',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container'),
    },
    'web3auth': {
        'base_url': 'https://web3auth.io/docs/sdk/pnp/web/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'ens_learn': {
        'base_url': 'https://docs.ens.domains/learn/protocol',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-learn',
    },
    'ens_web': {
        'base_url': 'https://docs.ens.domains/web/resolution',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-web',
    },
    'ens_registry': {
        'base_url': 'https://docs.ens.domains/registry/ens',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-registry',
    },
    'ens_resolver': {
        'base_url': 'https://docs.ens.domains/resolvers/public',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-resolver',
    },
    'ens_dao': {
        'base_url': 'https://docs.ens.domains/dao',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-dao',
    },
    'ens_ensip': {
        'base_url': 'https://docs.ens.domains/ensip/',
        'content_selector': '.article.prose',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='nav.flex'),
        'base_name': '-ensip',
    },
    'gnark_howto': {
        'base_url': 'https://docs.gnark.consensys.io/category/how-to',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-howto',
    },
    'gnark_reference': {
        'base_url': 'https://docs.gnark.consensys.io/Reference/api',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-reference',
    },
    'gnark_concepts': {
        'base_url': 'https://docs.gnark.consensys.io/category/concepts',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-menu'),
        'base_name': '-concepts',
    },
    'circom': {
        'base_url': 'https://docs.circom.io/getting-started/installation/',
        'content_selector': '.md-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.md-nav__item--section > nav:nth-child(3) > ul:nth-child(2)', selenium=True),
        'fetch_sidebar_func': fetch_sidebar_urls_wihtout_href
    },
    'suave': {
        'base_url': 'https://suave-alpha.flashbots.net/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'flashbots': {
        'base_url': 'https://docs.flashbots.net/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'solana': {
        'base_url': 'https://solana.com/docs',
        'content_selector': 'article.order-2',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.DevelopersContentPage_developers-content-page__sidebarGroup__FQ7HK', selenium=False),
    },
    'solana_spl': {
        'base_url': 'https://spl.solana.com/',
        'content_selector': '.docMainContainer_lg0V',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.menu', selenium=False),
    },
    'solana_labs': {
        'base_url': 'https://docs.solanalabs.com/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'raydium': {
        'base_url': 'https://docs.raydium.io/raydium/',
        'content_selector': 'main.r-1oszu61',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=False),
    },
    'jito': {
        'base_url': 'https://jito-foundation.gitbook.io/mev',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'jupiter': {
        'base_url': 'https://jupiter.readthedocs.io/en/latest/',
        'content_selector': '.document > div:nth-child(1)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.wy-nav-content-wrap', selenium=False),
    },
    'helius': {
        'base_url': 'https://docs.helius.dev/welcome/what-is-helius',
        'content_selector': 'main.r-1oszu61',
        'img_selector': 'div.r-14lw9ot:nth-child(3) > div:nth-child(1) > div:nth-child(2) > div:nth-child(1)',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-puj83k:nth-child(1) > div:nth-child(1) > div:nth-child(1)', selenium=False),
    },
    'orca': {
        'base_url': 'https://docs.orca.so/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'drift': {
        'base_url': 'https://docs.drift.trade/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=False),
    },
    'wormhole': {
        'base_url': 'https://docs.wormhole.com/wormhole',
        'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(1)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'pyth': {
        'base_url': 'https://docs.pyth.network/home',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=False),
    },
    'magic_eden': {
        'base_url': 'https://docs.magiceden.io/docs/wallet-introduction',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=False),
        'base_name': '-wallet-introduction',
    },
    'magic_eden_solana': {
        'base_url': 'https://docs.magiceden.io/reference/solana-overview',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=False),
        'base_name': '-solana',
    },
    'magic_eden_ordinals': {
        'base_url': 'https://docs.magiceden.io/reference/ordinals-overview',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=False),
        'base_name': '-ordinals',
    },
    'magic_eden_evm': {
        'base_url': 'https://docs.magiceden.io/reference/evm-api-overview',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=False),
        'base_name': '-evm',
    },
    'primev': {
        'base_url': 'https://docs.primev.com/english',
        'content_selector': 'div.r-13awgt0:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=False),
    },
    'bloxroute': {
        'base_url': 'https://docs.bloxroute.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.lg\:flex-row > div:nth-child(2)', selenium=False),
    },
    'across': {
        'base_url': 'https://docs.across.to/introduction/quickstart-guide',
        'content_selector': 'div.r-13awgt0:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=False),
    },
    'uma': {
        'base_url': 'https://docs.uma.xyz/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    '1inch_protocol': {
        'base_url': 'https://docs.1inch.io/docs/aggregation-protocol/introduction/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-aggregation-protocol',
    },
    '1inch_limit_order_protocol': {
        'base_url': 'https://docs.1inch.io/docs/limit-order-protocol/introduction/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-limit-order-protocol',
    },
    '1inch_spot_price_aggregator': {
        'base_url': 'https://docs.1inch.io/docs/spot-price-aggregator/introduction/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-spot-price-aggregator',
    },
    '1inch_fusion_swap': {
        'base_url': 'https://docs.1inch.io/docs/fusion-swap/introduction/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-fusion-swap',
    },
    '1inch_educational_resources': {
        'base_url': 'https://docs.1inch.io/docs/educational-resources/introduction',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-educational-resources',
    },
    'enso_finance': {
        'base_url': 'https://docs.enso.finance/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=False),
    },
    'uniswap_v4': {
        'base_url': 'https://docs.uniswapfoundation.org/',
        'content_selector': 'div.r-14lw9ot:nth-child(3) > div:nth-child(1) > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-14lw9ot:nth-child(3) > div:nth-child(1) > div:nth-child(2)', selenium=False),
    },
    'uniswap_concepts': {
        'base_url': 'https://docs.uniswap.org/concepts/overview',
        'content_selector': '.docMainContainer_TCnq',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=False),
        'base_name': '-concepts',
    },
    'uniswap_v3_sdk': {
        'base_url': 'https://docs.uniswap.org/sdk/v3/overview',
        'content_selector': '.docMainContainer_TCnq',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=False),
        'base_name': '-v3-sdk',
    },
    'uniswap_v3_contracts': {
        'base_url': 'https://docs.uniswap.org/contracts/v3/overview',
        'content_selector': '.docMainContainer_TCnq',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=False),
        'base_name': '-v3-contracts',
    },
    'aave': {
        'base_url': 'https://docs.aave.com/hub',
        'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(1)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
        'base_name': '-user-docs',
    },
    'aave_developer': {
        'base_url': 'https://docs.aave.com/developers',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
        'base_name': '-developer-docs',
    },
    'gho_developer': {
        'base_url': 'https://docs.gho.xyz/developer-docs/overview',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=False),
        'base_name': '-developer-docs',
    },
    'gho_concepts': {
        'base_url': 'https://docs.gho.xyz/concepts/overview',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=False),
        'base_name': '-concepts',
    },
    'namada': {
            'base_url': 'https://docs.namada.net/',
            'content_selector': 'article.nx-w-full',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=False),
    },
    'monad': {
            'base_url': 'https://docs.monad.xyz/',
            'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(1)',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'ambient': {
            'base_url': 'https://docs.ambient.finance/',
            'content_selector': '.lg\:flex-row > div:nth-child(2)',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'blocknative': {
            'base_url': 'https://docs.blocknative.com/',
            'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(1)',
            'img_selector': '.img_ev3q',
            'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'scroll': {
        'base_url': 'https://docs.scroll.io/en/getting-started/overview/',
        'content_selector': '#article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.nav-groups:nth-child(3)', selenium=False),
    },
    'optimism': {
        'base_url': 'https://docs.optimism.io/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=False),
    },
    'zksync_infra': {
        'base_url': 'https://docs.zksync.io/infra/',
        'content_selector': '#main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.sidebar-links:nth-child(1)', selenium=False),
        'base_name': '-infra',
    },
    'zksync_zkstack': {
        'base_url': 'https://docs.zksync.io/zk-stack/',
        'content_selector': '#main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.sidebar-links:nth-child(1)', selenium=False),
        'base_name': '-zkstack',
    },
    'zksync_build': {
        'base_url': 'https://docs.zksync.io/build/',
        'content_selector': '#main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.sidebar-links:nth-child(1)', selenium=False),
        'base_name': '-build',
    },
    'arbitrum': {
        'base_url': 'https://docs.arbitrum.io/welcome/get-started',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
    },
    'makerdao_collateral': {
        'base_url': 'https://collateral.makerdao.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'makerdao_governance': {
        'base_url': 'https://manual.makerdao.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'makerdao': {
        'base_url': 'https://docs.makerdao.com/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'automata': {
        'base_url': 'https://docs.ata.network/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'altlayer': {
        'base_url': 'https://docs.altlayer.io/altlayer-documentation/welcome/overview',
        'content_selector': 'div.r-14lw9ot:nth-child(3) > div:nth-child(1) > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=False),
    },
    'clusters': {
        'base_url': 'https://docs.clusters.xyz/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'gelato': {
        'base_url': 'https://docs.gelato.network/developer-services/introduction',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=False),
    },
    'opensea': {
        'base_url': 'https://docs.opensea.io/reference/api-overview',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#Explorer > nav:nth-child(1)', selenium=False),
    },
    'cargo': {
        'base_url': 'https://doc.rust-lang.org/cargo/index.html',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#sidebar', selenium=True),
    },
    'rust': {
        'base_url': 'https://doc.rust-lang.org/book/',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#sidebar', selenium=True),
    },
    'syncswap': {
        'base_url': 'https://syncswap.gitbook.io/syncswap',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'syncswap_second_selector': {
        'base_url': '.lg\:flex-row > div:nth-child(2)',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'zerolend': {
        'base_url': 'https://docs.zerolend.xyz/',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'muteio': {
        'base_url': 'https://wiki.mute.io/mute/koi-overview/master',
        'content_selector': 'div.r-13awgt0:nth-child(2) > div:nth-child(1)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=True),
    },
    'zkswap': {
        'base_url': 'https://docs.zkswap.finance/',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'mavxyz': {
        'base_url': 'https://docs.mav.xyz/',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'reactorfusion': {
        'base_url': 'https://docs.reactorfusion.xyz/',
        'content_selector': 'div.r-18u37iz:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.r-k200y', selenium=True),
    },
    'velocore': {
        'base_url': 'https://docs.velocore.xyz/',
        'content_selector': '#gitbook-main-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'solidity': {
        'base_url': 'https://docs.soliditylang.org/en/v0.8.25/',
        'content_selector': '.document',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.wy-menu', selenium=True),
    },
    'reth': {
        'base_url': 'https://paradigmxyz.github.io/reth/',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.chapter', selenium=True),
    },
    'mevio': {
        'base_url': 'https://docs.mev.io/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'illuvium': {
        'base_url': 'https://docs.illuvium.io/staking-v2',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'olympus': {
        'base_url': 'https://docs.olympusdao.finance/main/overview/intro/',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'olympus_technical': {
        'base_url': 'https://docs.olympusdao.finance/main/technical/overview/',
        'content_selector': '.docPage__5DB',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'ibc': {
        'base_url': 'https://ibc.cosmos.network/main',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'cosmostation': {
        'base_url': 'https://docs.cosmostation.io/apis',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'axelar': {
        'base_url': 'https://docs.axelar.dev/',
        'content_selector': '.mainBody',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.sideNav', selenium=True),
    },
    'dym': {
        'base_url': 'https://docs.dymension.xyz/',
        'content_selector': '.docItemContainer_Djhp',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'sei': {
        'base_url': 'https://www.docs.sei.io/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'quasar': {
        'base_url': 'https://docs.quasar.fi/overview/intro',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'stargate': {
        'base_url': 'https://stargateprotocol.gitbook.io/stargate',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'lavanetwork': {
        'base_url': 'https://docs.lavanet.xyz/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'cosmwasm': {
        'base_url': 'https://docs.cosmwasm.com/docs/',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'osmosis_outpost': {
        'base_url': 'https://docs.osmosis.zone/osmosis-outpost/',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'osmosis_core': {
        'base_url': 'https://docs.osmosis.zone/osmosis-core',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'osmosis_educate': {
        'base_url': 'https://docs.osmosis.zone/overview/educate',
        'content_selector': '.docMainContainer_gTbr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
    },
    'akash': {
        'base_url': 'https://akash.network/docs/',
        'content_selector': 'div.w-full:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.md\:block:nth-child(1)', selenium=True),
    },
    'assetmantle': {
        'base_url': 'https://docs.assetmantle.one/Overview/',
        'content_selector': '.md-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='ul.md-nav__list:nth-child(1)', selenium=True),
    },
    'canto': {
        'base_url': 'https://docs.canto.io/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'fetch': {
        'base_url': 'https://fetch.ai/docs/guides',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'dydx': {
        'base_url': 'https://docs.dydx.exchange/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'stride': {
        'base_url': 'https://docs.stride.zone/docs/getting-started',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=True),
    },
    'neutron': {
        'base_url': 'https://docs.neutron.org/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'band': {
        'base_url': 'https://docs.bandchain.org/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'secret': {
        'base_url': 'https://docs.scrt.network/secret-network-documentation',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'irisnet': {
        'base_url': 'https://www.irisnet.org/docs/',
        'content_selector': '.theme-default-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.sidebar', selenium=True),
    },
    'astaria': {
        'base_url': 'https://docs.astaria.xyz/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'brink': {
        'base_url': 'https://docs.brink.trade/docs/introduction',
        'content_selector': '.rm-Article',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#hub-sidebar', selenium=True),
    },
    'li.fi': {
        'base_url': 'https://docs.li.fi/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'cow.fi': {
        'base_url': 'https://docs.cow.fi/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
        'base_name': '-aggregation-protocol',
    },
    'carbondefi': {
        'base_url': 'https://docs.carbondefi.xyz/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'flood': {
        'base_url': 'https://docs.flood.bid/',
        'content_selector': 'article.nx-w-full',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.nextra-sidebar-container', selenium=True),
    },
    'relay': {
        'base_url': 'https://docs.relay.link/what-is-relay',
        'content_selector': '.flex-row',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#sidebar', selenium=True),
    },
    'agoric': {
        'base_url': 'https://docs.agoric.com/guides/getting-started/',
        'content_selector': '.VPDoc > div:nth-child(1) > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.aside', selenium=True),
    },
    'alchemy-api': {
        'base_url': 'https://docs.alchemy.com/reference/api-overview',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#Explorer > nav:nth-child(1)', selenium=True),
        'base_name': '-api-overview',
    },
    'alchemy-tutorial': {
        'base_url': 'https://docs.alchemy.com/docs/tutorials-overview',
        'content_selector': '#content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#Explorer > nav:nth-child(1)', selenium=True),
        'base_name': '-tutorials-overview',
    },
    'biconomy': {
        'base_url': 'https://docs.biconomy.io/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'conduit': {
        'base_url': 'https://docs.conduit.io/docs/introduction/getting-started/',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'connext': {
        'base_url': 'https://docs.connext.network/',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'truffle': {
        'base_url': 'https://archive.trufflesuite.com/docs/truffle/how-to/debug-test/use-the-truffle-debugger/',
        'content_selector': '.md-content',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='div.md-sidebar:nth-child(1) > div:nth-child(1)', selenium=True),
    },
    'scribbles': {
        'base_url': 'https://docs.scribble.codes/',
        'content_selector': '.lg\:flex-row > div:nth-child(2) > div:nth-child(1)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
    },
    'infura': {
        'base_url': 'https://docs.infura.io/api',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'tessera': {
        'base_url': 'https://docs.tessera.consensys.io/overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'hyperledger-public': {
        'base_url': 'https://besu.hyperledger.org/public-networks',
        'content_selector': '.docMainContainer_TBSr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
        'base_name': '-public',
    },
    'hyperledger-private': {
        'base_url': 'https://besu.hyperledger.org/private-networks',
        'content_selector': '.docMainContainer_TBSr',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
        'base_name': '-private',
    },
    'quorum': {
        'base_url': 'https://docs.goquorum.consensys.io/deploy/install/overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'ethsigner': {
        'base_url': 'https://docs.ethsigner.consensys.io/overview',
        'content_selector': '.docItemCol_VOVn',
        'img_selector': '.img_ev3q',
        'next_button_selector': '.pagination-nav__link--next',
    },
    'metamask_wallet': {
        'base_url': 'https://docs.metamask.io/wallet/',
        'content_selector': '.docItemCol_z5aJ',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
        'base_name': '-wallet',
    },
    'metamask_snaps': {
        'base_url': 'https://docs.metamask.io/snaps/',
        'content_selector': '.docItemCol_z5aJ',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.theme-doc-sidebar-container', selenium=True),
        'base_name': '-snaps',
    },
    'codefi': {
        'base_url': 'https://documenter.getpostman.com/view/5733481/SW7T8XSY#intro',
        'content_selector': '.layoutstyles__ContentWrapper-sc-sfl92e-5',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='.layoutstyles__FixedWidthContainer-sc-sfl92e-4', selenium=True),
        'base_name': '-snaps',
    },
    'dapdap': {
        'base_url': 'https://docs.dapdap.net/',
        'content_selector': '.lg\:flex-row > div:nth-child(2).lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
        'base_name': '-snaps',
    },
    'espressosys': {
        'base_url': 'https://docs.espressosys.com/cape',
        'content_selector': '.lg\:flex-row > div:nth-child(2)',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='aside.relative', selenium=True),
        'base_name': '-snaps',
    },
    'aperture': {
        'base_url': 'https://docs.aperture.finance/docs',
        'content_selector': 'body > div.scroll-nojump > div > div',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='body > div.scroll-nojump > div > aside', selenium=True),
        'base_name': '-snaps',
    },
    'dune': {
        'base_url': 'https://docs.dune.com/home',
        'content_selector': '#content-area',
        'img_selector': '.img_ev3q',
        'crawl_func': partial(crawl_sidebar, sidebar_selector='#sidebar > div > ul', selenium=True),
    },
}
